### ISSUE TITLE
evaluate quote problem

### ISSUE THREAD

**Issue by woodsbox** [chrome-php/headless-chromium-php#15]
$evaluation = $page->evaluate(
'(() => {
        element1.setAttribute("name", 'I need to have a quote " in here');

the ' quote is not working so I end up with:
        element1.setAttribute("name", "I need to have a quote " in here");

But of course that doesn't work.
Any tips advice?

**Comment by gsouf** [comment]
Hi @woodsbox 

That's not working because the single quotes you are using in the javascript code are conflicting with the outter quotes you use in php. 

FYI that's a general php question not related to the project and you could find your answer by googling: https://stackoverflow.com/a/7999163/1278479
No offense just saying because issues here should be dedicated to project related issues and you have a lot of places you can find good support for this kind of php related question and time we would spend here answering this kind of question is time that wont be used for the project itself

**Comment by woodsbox** [comment]
Hi @gsouf well I of course already tried: 
element1.setAttribute("name", "I need to have a quote \" in here");

That is also not working the output on the page will be:

<input name="I need to have a quote " in here"

**Comment by gsouf** [comment]
``element1.setAttribute("name", "I need to have a quote \\" in here");``

**Comment by woodsbox** [comment]
Thats what I would expect but that doesn't work the evaluation is not executed in that case.

**Comment by woodsbox** [comment]
If you want to try this is the code:

`$evaluation = $page->evaluate(
'(() => {
        var form = document.createElement("form");
        document.body.appendChild(form);
        form.method = "POST";
        form.action = "index.php";
        form.enctype = "text/plain";
        var element1 = document.createElement("INPUT");
        element1.setAttribute("name", "I need to have a quote \\\" in here");
        form.appendChild(element1);
        //form.submit();
    })()'
 );
`

**Comment by gsouf** [comment]
When you have this javascript code: ``element1.setAttribute("name", "I need to have a quote \\\" in here");``

If you translate it to a php string it becomes:

``$js = 'element1.setAttribute("name", "I need to have a quote \\\\\\" in here");'``
