### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by platinumuser** [chrome-php/headless-chromium-php#158]
Hello
How to use a proxy server with authorization login and password?
I indicate such a parameter

`'customFlags' => ['--proxy-server=http://proxy.example.com:8000']`

**Comment by alex-rsk** [comment]
There's no direct possibility in Chromium to use proxies with credentials, you may use proxy forwarding only.  check  [mitmproxy](https://mitmproxy.org/)

**Comment by TimIgoe** [comment]
Its perfectly valid to use proxies with authentication - you just have to catch and respond to the relevant messages in code. (been doing it for many many months)

**Comment by alex-rsk** [comment]
> Its perfectly valid to use proxies with authentication - you just have to catch and respond to the relevant messages in code. (been doing it for many many months)
Firstly, I wrote "**direct**" possibility. Secondly, your way (using Fetch.continueRequest) could cause  segmentation fault sometimes, if you send authorization response to the socket  **after** browser process destroyed.
  Also,  it causes opening empty tabs with 0.0.0.0 (i guess, because browser getting some authorizationRequests **before** you are plugging in to the socket.
I'm for stability. So I chose abovementioned way.
