### ISSUE TITLE
Is there a way to run chrome in headful mode on apache webserver?

### ISSUE THREAD

**Issue by ShamanHead** [chrome-php/headless-chromium-php#241]
I faced with a problem that I can't to resolve. I need to run chrome in headful mode, but whatever I do I see this error:
`[Uncaught RuntimeException: Chrome process stopped before startup completed. Additional info: [40326:40326:0720/054132.705400:ERROR:browser_main_loop.cc(1409)] Unable to open X display. in]`
I've tried to install xvfb, but error is still the same. All chrome deps is installing, what I need to do?

**Comment by enricodias** [comment]
I'm not sure whats the purpose of trying to run chrome in headful mode with xvfb since you won't be getting a gui either way, but just starting xvfb should be enough to make a browser work. There are plenty of questions about this issue in StackOverflow, have you tried searching there?

If you find something related to how this package executes chrome that we could change to fix this issue, feel free to reply here.

**Comment by devinyasas** [comment]
Did you try launch browser by setting `--no-sandbox => true,` ?

**Comment by wbeugene** [comment]
If you successfully run chrome from terminal and see it working window then try add 
`$_ENV = getenv();`
at beginning of your script, or check https://www.php.net/manual/en/ini.core.php#ini.variables-order  and make correction to options
because of basic php config is not forming $_ENV which later used by symfony/process as passing enviroments variables

**Comment by wobal** [comment]
Add : `'envVariables'  => ['DISPLAY' =>':0.0']` in createBrowser with the last version of chrome-php (1.0).
That solved the problem for me.
