### ISSUE TITLE
New tab is getting created

### ISSUE THREAD

**Issue by codes-begin** [chrome-php/headless-chromium-php#257]
Hi, Anyone got solutions to this [issue #250 ](https://github.com/chrome-php/chrome/issues/250). I want to work in one tab only. My code is creating a new tab everytime. below is my code
$socketFile = 'tmp';
$browser = null;
if (file_exists($socketFile)) {
$socket = \file_get_contents($socketFile);
try {
$browser = \HeadlessChromium\BrowserFactory::connectToBrowser($socket, [
'debugLogger' => 'php://stdout',
]);
} catch (\HeadlessChromium\Exception\BrowserConnectionFailed $e) {
echo "No browser";
}
}

    if (!$browser) {
        $factory = new \HeadlessChromium\BrowserFactory();
        $browser = $factory->createBrowser([
            'headless' => false,
            'keepAlive' => true,
        ]);
        file_put_contents($socketFile, $browser->getSocketUri());
    }
    $page = $browser->createPage();

**Comment by octoper** [comment]
Yeah every time you call `$browser->createPage()` a new tab will be created also you have the option `keepAlive` as true so that means that every time you call your script it will use the same browser and it will open a new tab you must either close the browser at the end of your code or if you want to change pages inside the same run of the file you just do 
```php
$page->navigate('https://example.com')->waitForNavigation();
// Do something

$page->navigate('https://github.com')->waitForNavigation();
// Do something
```
