### ISSUE TITLE
Error: Could not find node with given id

### ISSUE THREAD

**Issue by santossoares** [chrome-php/headless-chromium-php#469]
I got an issue with this library. I think its a bug.

When i use the  querySelectorAll function, and iterate over its elements, the code works fine!

While on the loop iterating with the elements, and using another selector on the $page instance, then it looses the "reference to the elements", it throws the following error: Could not find node with given id.

Can anyone solve this?

Thanks!

Here is the sample code:

```php
use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();

$browser = $browserFactory->createBrowser([
    'headless' => false
]);

$page = $browser->createPage();
$page->navigate('http://google.com')->waitForNavigation();

$elements = $page->dom()->querySelectorAll('.pHiOh');

foreach ($elements as $e) {
    echo($e->getText()).PHP_EOL;
    
    // This new selector causes error on the previous line!
    // Just remove this line and the code works!
    $buttons = $page->dom()->querySelectorAll('button');

    // ERROR: Uncaught HeadlessChromium\Exception\DomException: -32000 - Could not find node with given id
}

sleep(3);
$browser->close();
```

**Comment by aravael** [comment]
Hi @santossoares , your remark is fair enough. I noticed such behavior a while ago and I think it's because `$page->dom()` creates a new Dom object every time it is invoked. Definitely need clarification from @enricodias .
In the meanwhile a workaround is this:
```
use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();

$browser = $browserFactory->createBrowser([
    'headless' => false
]);

$page = $browser->createPage();
$page->navigate('https://google.com')->waitForNavigation();

$elements = $page->dom()->querySelectorAll('.pHiOh');

for ($i = 0; $i < count($elements); $i++) {
    $elements = $page->dom()->querySelectorAll('.pHiOh');

    echo $elements[$i]->getText();

    $buttons = $page->dom()->querySelectorAll('button');
}
```

**Comment by santossoares** [comment]
Thanks for the reply! I got some workaround too!
I just call the $page->dom() only once, with for example body element, and store it in a variable.
Then if i want to search for another selector, i use that variable that contains the body element and search using the queryselector from the variable.

$body = $page->dom('body');
$body->querySelectorAll('.someclass');

This way, the dom is never replaced like when you call the $page->dom() again.

**Comment by enricodias** [comment]
Apparently calling `DOM.getDocument` makes chrome update the node ids, making the old ids stale. `Page::dom()` always creates a new object of `Dom::class` that queries the browser with `DOM.getDocument`. I'm not sure if this was the intended outcome when @Seriyyy95 created the class.

In the example code, both `Node::querySelectorAll()` and `Node::getHTML()` (called by getText) actually query the browser to get the content, which is a good thing since the DOM can change without our interaction, and stores the node ids in the actual `Node` object. When `Page::dom()` is called between them, the node ids get updated.

Storing the `Dom` object in a variable may solve the issue in this case, but since the DOM can change even without our interaction this problem may persist in other pages. Maybe in the future we could have a virtual dom that stores the entire dom content and listen to the `DOM.documentUpdated` event to keep it always updated.

**Comment by Seriyyy95** [comment]
I didn't know that calling `DOM.getDocument` makes chrome update the node ids when I created this class. I think we do not need to save a copy for the entire dom, it will be enough to have one instance of `Dom` and update the value for the root node id when the `DOM.documentUpdated` is caught. We can do something like this:

```
$page->getSession()->on('method:DOM.documentUpdated', function () {
   //call DOM.getDocument and update node id
});
```

But there are multiple issues which I don't know to solve:

- I need to handle all events from Chrome as soon as possible to do this. But the current realization of `Wrench\Socket\\AbstractSocket::receive()` blocks execution when there are no messages in the socket. So I can call `$page->getSession()->getConnection()->readData() `only when I wait data from Chrome. When I call it in the `Page::dom() `method it can block execution until the next event is received.
- In my tests, Chrome fires two `DOM.documentUpdated` events for one reloading. All code, that is executed before the second event is processed will fail because the node Id is incorrect.

**Comment by enricodias** [comment]
Updating the `Dom` alone wouldn't be enough, every `Node` object must have it's id updated. I don't think there's a way to find the new id for every node and since we basically only save the id of each node, every old `Node` object become useless. Maybe we could map the entire dom to a [DOMDocument](https://www.php.net/manual/en/class.domdocument.php) class and returns a copy of it on each call. It can be a new class to keep backwards compatibility.

There's also the possibility of the dom being updated and an old `Node` points to a new unrelated object that happens to have the same id, if chrome reuses old ids.

**Comment by Seriyyy95** [comment]
When the page is completely updated (on `DOM.documentUpdated`), we can be sure that only one node exists - the root node. All other nodes may not exist, and we should not try to find new IDs for them. Instead, we can simply mark them as stale, as Selenium does. The main idea of the `Dom` class is to provide real-time access to Chrome's DOM tree, it can not only fetch text and attributes from elements, but also scroll the page, type text, send files, get current coordinates, click on elements, and more. By caching the DOM, the class loses all of these features. If it is necessary to work with a non-changing DOM, it is possible to fetch the HTML from the page and use `symfony/dom-crawler`. 

Changing element IDs on a page without reloading it is an issue for all tools for web automation and scraping. I looked at [Rod](https://github.com/go-rod/rod) project, they use `Runtime.RemoteObject.object.id` instead of `NodeId`, but I think that the IDs are changed as well as nodeIds. It needs more testing.

**Comment by santossoares** [comment]
How does puppeteer handle this internally? Since its using the chrome dev tools to accomplish the same tasks.

**Comment by Seriyyy95** [comment]
> How does puppeteer handle this internally? Since its using the chrome dev tools to accomplish the same tasks.

It interesting, but I have no enough experience with Node.js and Puppeteer to find out how they implement it. It looks like puppeteer provides access to element attributes and their inner text even if the element is stale, but throws an exception when I try to interact with this element. 

I guess it is possible to use `DOM.describeNode` request to get all attributes on node initialization, and then update them on `DOM.attributeModified` and `DOM.attributeRemoved` events. Inner text can be fetched using `DOM.describeNode` too, but requires  doing foreach through all its children. Something like this:

```
    private function parseInnerText(array $nodes): string
    {
        $text = '';

        foreach ($nodes as $node) {
            if ($node['nodeType'] === 3) {
                // If the node is a text node, concatenate its nodeValue property to the $text variable
                $text .= $node['nodeValue'];
            } else if ($node['nodeType'] === 1) {
                // If the node is an element node, recursively call the parseInnerText function with its children
                $text .= $this->parseInnerText($node['children']);
            }
        }

        return $text;
    }
```

The `DOM.setChildNodes` event can be used to keep node inner text updated. But I not sure that this is a good idea for performance. Maybe it can be done only for nodes with small number of children.

**Comment by Seriyyy95** [comment]
I can use `\Wrench\Client::waitForData` from upcoming Wrench 1.7 to call `readData()` only when the socket has any data available to avoid blocking during event processing. So now, I can store Dom in a variable and keep the root node id always updated. It will fix `-32000 - Could not find node with given id`. 

I am not sure if it is better to prepare a pull request now or wait until Wrench 1.7 is released to avoid merge conflicts.

**Comment by GrahamCampbell** [comment]
Please don't wait for 1.7 to be released. I likely won't release it until there's PRs on this repo that use it.
