### ISSUE TITLE
google chrome optimization

### ISSUE THREAD

**Issue by ayd-is** [chrome-php/headless-chromium-php#496]
hi!
google chrome consumes a lot of resources,
is there an option to cut most of the functionality with customflags?

I would like to run different browser sessions in large numbers (about 100-200 pieces) on the same server?

maybe there is a light version of google chrome for ubuntu?

thanks in advance for your reply!

**Comment by enricodias** [comment]
I don't think there are ways to make it lighter with custom flags. You can disable js, but that will also break most websites. Disabling images will basically only save bandwidth.

You can try using the same chrome instance with multiple tabs in the same session in parallel, but you'll still have at least one process per tab and almost the same amount of ram. I wouldn't worry too much about the ram usage if that's the only thing running in the server, using swap should be fine since most of the time the processes will be waiting for slow I/O operations.
