### ISSUE TITLE
running phpstan on Ubuntu24.04 attempst to run reg

### ISSUE THREAD

**Issue by divinity76** [chrome-php/headless-chromium-php#657]
```
$ vendor/bin/phpunit
PHPUnit 10.5.37 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.6
Configuration: /home/hans/projects/chrome/phpunit.xml.dist

.F.sh: 1: reg: not found
.

.....F......F..............................................  63 / 156 ( 40%)
(...)
```

have not figured out why, but that `.F.sh: 1: reg: not found`  indicate that \HeadlessChromium\AutoDiscover::__construct was passed a $osFamily callable that deduced Ubuntu24.04 is a Microsoft Windows operating system 🤷‍♂️ 

edit1: the actual cb originates from https://github.com/chrome-php/chrome/blob/dc463f0444b4a804046b7713222c0ccd1aa7b67e/tests/AutoDiscoverTest.php#L82

**Comment by enricodias** [comment]
That makes sense because the test is overwriting the `PHP_OS_FAMILY` to make `guessChromeBinaryPath` calls `getFromRegistry`, which should return null and fallback to the default path that also ends with `.exe`. Running the test on windowswould actually return the path from the registry and the test will past either way.

The `shell_exec` is already inside a try catch block and even with a `@` to suppress errors. I'm not sure where the `.F.` comes from, but the `reg: not found` is expected as "reg" doesn't exists on linux.

**Comment by divinity76** [comment]
the reg test should be skipped when not running on Windows.

**Comment by enricodias** [comment]
The test is forcing that path so that the method can be tested regardless of which platform the tests are running.

**Comment by divinity76** [comment]
@enricodias well it should not do that. the reg test should be skipped, not forced, when not running on Windows.

**Comment by divinity76** [comment]
@enricodias forcing a platform-specific test to run on the wrong platform where it is guaranteed to fail every time makes no sense. A waste of CPU cycles if nothing else.

**Comment by enricodias** [comment]
But the test itself is not failing, it's just adding that extra output when the shell exec tries to run. We are still testing that everything around it works and that it fails in a way that triggers the default values. Shell exec can fail on windows too if it's in the disabled functions. Since our pipeline only runs on linux, skipping that test may allow that feature to break silently in the future, in a way that it crashes or doesn't use the default values.
